// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB6p0ZeW6rgznBcIyRtV4Go3rfqmkRR0rQ',
    appId: '1:597436212473:web:9cf4985a4a5dff0704ae28',
    messagingSenderId: '597436212473',
    projectId: 'phone-booth-c2cd7',
    authDomain: 'phone-booth-c2cd7.firebaseapp.com',
    storageBucket: 'phone-booth-c2cd7.appspot.com',
    measurementId: 'G-89HJH6SC26',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB3wzvnqFkmPa0hc0iYj3qt167ru2BeRc0',
    appId: '1:597436212473:android:8e9bfb1318653b3104ae28',
    messagingSenderId: '597436212473',
    projectId: 'phone-booth-c2cd7',
    storageBucket: 'phone-booth-c2cd7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBb0izwWXAAdj36gaM175RbNgT1GGQJHkA',
    appId: '1:597436212473:ios:c18c8755c962f21804ae28',
    messagingSenderId: '597436212473',
    projectId: 'phone-booth-c2cd7',
    storageBucket: 'phone-booth-c2cd7.appspot.com',
    androidClientId:
        '597436212473-b55elqq7tfopv5e4lf4cpof4e3p4tm0f.apps.googleusercontent.com',
    iosClientId:
        '597436212473-lgtner9n5led02hk2ns7suloar25b3rb.apps.googleusercontent.com',
    iosBundleId: 'com.phonebooth.cabinApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBb0izwWXAAdj36gaM175RbNgT1GGQJHkA',
    appId: '1:597436212473:ios:c18c8755c962f21804ae28',
    messagingSenderId: '597436212473',
    projectId: 'phone-booth-c2cd7',
    storageBucket: 'phone-booth-c2cd7.appspot.com',
    androidClientId:
        '597436212473-b55elqq7tfopv5e4lf4cpof4e3p4tm0f.apps.googleusercontent.com',
    iosClientId:
        '597436212473-lgtner9n5led02hk2ns7suloar25b3rb.apps.googleusercontent.com',
    iosBundleId: 'com.phonebooth.cabinApp',
  );
}
